### ISSUE TITLE
Is the secondary top-bar necessary?  

### ISSUE THREAD

**Issue by micahlt** [scratchsuite/apidocs#12]
This is purely design-related and certainly not high priority.  However, I was wondering - what's the reasoning for the second top bar?  Currently it seems like a waste of pixels since it just mimics the lower bar, doesn't contribute any extra navigation, and doesn't match the color scheming of the rest of the site.  Maybe it's just me, but I feel that the site would be cleaner with only one top bar.  

![image](https://user-images.githubusercontent.com/28816297/111041393-94b84180-83fd-11eb-9e35-04c124c40d13.png)

**Comment by FunctionalMetatable** [comment]
I just put the topbar (I'm still testing it rn) so there's links to other stuff included with scratchsuite. If that's the case, I'll delete it.

**Comment by FunctionalMetatable** [comment]
Resolved #13.
